#!/bin/zsh


ksp_install=/cygdrive/e/KSP/ksp-win64-1.2.2-mechval/KSP_win64

bindir_cs=MechVal/MechVal/bin/Debug
bindir_cpp=MechValCore/x64/Debug

#bindir_cs=MechVal/MechVal/bin/Release
#
echo Removing previous install...
rm -vfr $ksp_install/GameData/MechVal
echo

echo Installing...
cp -vfr GameData/MechVal  $ksp_install/GameData

mkdir -vp  $ksp_install/GameData/MechVal/Plugins
cp -vfr $bindir_cs/MechVal.dll  $ksp_install/GameData/MechVal/Plugins
cp -vfr $bindir_cpp/MechValCore.dll  $ksp_install/KSP_x64_Data/Mono




